name: get_central_route
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Akka CLI
        uses: akka/setup-akka-cli-action@v1
        with:
          token: ${{ secrets.AKKA_TOKEN }}
          project-id: ${{ secrets.AKKA_PROJECT_ID }}
      - name: Get Central Route
        id: central_route
        run: |
          echo "Get Central Route"
          central_route_json=$(akka service get central -o json)
          
          # Extract the host from the first routes entry
          route_host=$(echo "$central_route_json" | jq -r '.routes[0].spec.host // "not-found"')
          
          echo "Route host: $route_host"
          echo "host=$route_host" >> $GITHUB_OUTPUT
      
      - name: Use Central Route Host
        run: |
          echo "Central service host: ${{ steps.central_route.outputs.host }}"
          echo "Full URL: https://${{ steps.central_route.outputs.host }}"