name: get_central_route
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Akka CLI
        uses: akka/setup-akka-cli-action@v1
        with:
          token: ${{ secrets.AKKA_TOKEN }}
          project-id: ${{ secrets.AKKA_PROJECT_ID }}
      - name: Get Central Route
        id: central_route
        run: |
          echo "Get Central Route"
          central_route_json=$(akka service get central -o json)
          echo "$central_route_json"
          
          # Store for later use (escape newlines for GitHub Actions)
          echo "json_output<<EOF" >> $GITHUB_OUTPUT
          echo "$central_route_json" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # Or if you want to extract specific fields with jq:
          # route_url=$(echo "$central_route_json" | jq -r '.url // "not-found"')
          # echo "route_url=$route_url" >> $GITHUB_OUTPUT
      
      - name: Use Central Route Data
        run: |
          echo "Retrieved JSON:"
          echo '${{ steps.central_route.outputs.json_output }}'