name: store

on:
  push:
    branches: [ main ]
    paths: 
	- 'store/**'
	
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Akka CLI
        uses: akka/setup-akka-cli-action@v1
        with:
          token: ${{ secrets.AKKA_TOKEN }}
          project-id: ${{ secrets.AKKA_PROJECT_ID }}
      - run: echo "Build & deploy stores"
      - name: List projects
        run: akka projects list

	